{"cells":[{"cell_type":"markdown","metadata":{"colab_type":"text","id":"xFrzPlyoikd9"},"source":["What do you think will happen to the accuracy of training a neural network as the number of layers increases? Try training a neural network for the MNIST data using more layers to see what happens. Speculate as to why you are seeing what you are seeing."]},{"cell_type":"code","execution_count":5,"metadata":{"colab":{},"colab_type":"code","executionInfo":{"elapsed":27038,"status":"ok","timestamp":1593115578691,"user":{"displayName":"Michael Littman","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh1OI1zp1NevMSZ87UN47k8bTZ--Ijr4v3ORV33Vg=s64","userId":"06751891446459829367"},"user_tz":240},"id":"UZ27Nqb8TBKx"},"outputs":[{"name":"stderr","output_type":"stream","text":["/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/sklearn/datasets/_openml.py:1022: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.\n","  warn(\n"]}],"source":["# Read in the mnist digit dataset\n","\n","from sklearn.datasets import fetch_openml\n","from sklearn.model_selection import train_test_split\n","from sklearn.utils import check_random_state\n","import random\n","from sklearn import tree\n","import matplotlib.pyplot as plt\n","import numpy as np\n","from sklearn.neural_network import MLPClassifier\n","\n","X, y = fetch_openml('mnist_784', version=1, return_X_y=True)"]},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"KB0MV4C1jCAC"},"source":["Next, we will divide the data into a training set and test set, randomly selecting 5000 examples for training"]},{"cell_type":"code","execution_count":6,"metadata":{"colab":{},"colab_type":"code","executionInfo":{"elapsed":1638,"status":"ok","timestamp":1593115580332,"user":{"displayName":"Michael Littman","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh1OI1zp1NevMSZ87UN47k8bTZ--Ijr4v3ORV33Vg=s64","userId":"06751891446459829367"},"user_tz":240},"id":"IJ2-XGCVTBK3"},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3505, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"/tmp/ipykernel_131631/3822277171.py\", line 5, in <module>\n","    X = X[permutation]\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/pandas/core/frame.py\", line 2806, in __getitem__\n","    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/pandas/core/indexing.py\", line 1552, in _get_listlike_indexer\n","    self._validate_read_indexer(\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/pandas/core/indexing.py\", line 1640, in _validate_read_indexer\n","    raise KeyError(f\"None of [{key}] are in the [{axis_name}]\")\n","KeyError: \"None of [Int64Index([10840, 56267, 14849, 62726, 47180, 61640, 52730, 21847, 20394,\\n            45806,\\n            ...\\n            52620, 39512, 48600, 55026, 41993, 21243, 45891, 42613, 43567,\\n            68268],\\n           dtype='int64', length=70000)] are in the [columns]\"\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2102, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1310, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1199, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1052, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 953, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1005, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/stack_data/core.py\", line 455, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/pygments/style.py\", line 66, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","  File \"/home/fahadaslam/anaconda3/envs/mlpython3.8/lib/python3.8/site-packages/pygments/style.py\", line 33, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["train_samples = 5000\n","\n","random_state = check_random_state(0)\n","permutation = random_state.permutation(X.shape[0])\n","X = X[permutation]\n","y = y[permutation]\n","X = X.reshape((X.shape[0], -1))\n","\n","X_train, X_test, y_train, y_test = train_test_split(\n","    X, y, train_size=train_samples, test_size=10000)"]},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"CTpGs2l-kdOs"},"source":["Now, we will try 10 hidden units in each of 1 to 10 layers, keeping track of the min/mean/max accuracy of models at each number of layers over ten runs.\n","\n"]},{"cell_type":"code","execution_count":5,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":187},"colab_type":"code","executionInfo":{"elapsed":1256680,"status":"ok","timestamp":1593118567261,"user":{"displayName":"Michael Littman","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh1OI1zp1NevMSZ87UN47k8bTZ--Ijr4v3ORV33Vg=s64","userId":"06751891446459829367"},"user_tz":240},"id":"FFoZESbCupY3","outputId":"bcd8e80b-764d-4472-c55d-9435d87f7a2e"},"outputs":[{"name":"stdout","output_type":"stream","text":["1 0.8696 0.88229 0.8923\n","2 0.8584 0.8683400000000001 0.878\n","3 0.8442 0.85788 0.8673\n","4 0.8638 0.8722900000000001 0.8782\n","5 0.8817 0.88993 0.9004\n","6 0.8868 0.8956899999999999 0.9046\n","7 0.8987 0.9082800000000001 0.9179\n","8 0.9074 0.9196899999999999 0.9272\n","9 0.891 0.9213099999999999 0.936\n","10 0.9117 0.9243399999999999 0.9389\n"]}],"source":["reps = 10\n","for i in range(1,11):\n","  nhidden = i*[100]\n","  accsum,accmin,accmax = 0.0,1.0,0.0\n","  for r in range(reps):\n","    clf = MLPClassifier(hidden_layer_sizes=nhidden, max_iter = 10000)\n","    clf.fit(X_train, y_train)\n","    score = clf.score(X_test, y_test)\n","    accsum += score\n","    accmin = min(accmin, score)\n","    accmax = max(accmax, score)\n","  print(i, accmin, accsum/reps, accmax)"]}],"metadata":{"colab":{"collapsed_sections":[],"name":"L04qs.ipynb","provenance":[]},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.19"}},"nbformat":4,"nbformat_minor":0}
